### ISSUE TITLE
Add support for MacOS

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/clix#4]

**Comment by kakshay21** [comment]
These are my finding with the installation process of clix in macos 10.12.5
First of all the installation process in mac is very troublesome. Clix is installed in my system but it's not functioning at all.
Let me explain the problem
First macos user has to install this [package](https://pypi.python.org/pypi/python-xlib) and once it's installed user can proceed to follow the instruction given in README.md
tkinter has some issues with macos as i get this error
```(env) AKSHAYs-MacBook-Pro:clix akshay$ python clix.py
Traceback (most recent call last):
  File "clix.py", line 172, in <module>
    main()
  File "clix.py", line 168, in main
    clipboard(utils.clips)
  File "/Users/akshay/Desktop/Bounty/clix/clix/gui.py", line 39, in __init__
    "icon.png"))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 3366, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 3320, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "/Users/akshay/Desktop/Bounty/clix/clix/icon.png"
```
I tried to change the image format but that didn't work
And then i found that this could be resolved once we update tcl/tk or install [this](https://www.python.org/download/mac/tcltk/#activetcl-8-5-18-0)
I tried that too and this removed the above error, partly.
And Now the program was successfully running but still not functioning.
Now since this is the issue with macos that it does not allow to record user activity either through mouse or keyboard as the way clix is written with respect to Linux.
I even tried further to install X11 or XQuartz from [here](https://support.apple.com/en-in/HT201341)
```
RECORD extension not found
```
So now coming to question how would like to go forward from here @championswimmer

**Comment by himanshuc3** [comment]
It basically seems to be an error with python-Xlib. Though in README its given to install Xlib using apt-get, mac doesn't have it I think. We have homebrew as a package manager.
