### ISSUE TITLE
Update the Readme

### ISSUE THREAD

**Issue by apezoidal** [coding-blocks/clix#9]
Hi sir,
I use ubuntu 16.04, and I use python by anaconda. I repeatedly ran the command 
` $ sudo apt-get install python-xlib`
but for me the error : "no module named Xlib " satisfied after typing the following:
`pip install python3_xlib` 
as the code in Clix couldnot access the Xlib module present in root.
I would like to update the readme for the same

**Comment by dibyadas** [comment]
@apezoidal Strange :confused:  Exactly the opposite worked for me.
Can you post more details about your error?

**Comment by apezoidal** [comment]
I was getting the following error: 
`clix
Traceback (most recent call last):
  File "/home/anika/anaconda2/bin/clix", line 7, in <module>
    from clix.clix import main
  File "/home/anika/anaconda2/lib/python2.7/site-packages/clix/__init__.py", line 1, in <module>
    from .clix import *
  File "/home/anika/anaconda2/lib/python2.7/site-packages/clix/clix.py", line 6, in <module>
    from .pyxhook import HookManager
  File "/home/anika/anaconda2/lib/python2.7/site-packages/clix/pyxhook.py", line 42, in <module>
    from Xlib import X, XK, display
ImportError: No module named Xlib
`

**Comment by dibyadas** [comment]
@apezoidal I just noticed. It seems you are using python 3, since `pip install python3_xlib` worked for you. So, instead of `sudo apt-get install python-xlib` , it should have been `sudo apt-get install python3-xlib`

Correct me If I'm wrong.

**Comment by apezoidal** [comment]
@dibyadas  the problem was that by `sudo install` the xlib was being downloaded in root and my clix code was not able to access it. While, `pip install python3_xlib` installed the module in the anaconda folder. Moreover, though I overcame "No module named Xlib" error, further errors came up. According to me the clix code is written in python-2.7 and thus the python-3 xlib library is not compatible to it ( its just a guess).
Advice me what to do.

**Comment by dibyadas** [comment]
@apezoidal The clix source code is compatible with both Python 3 and 2. I suggest you try this `sudo apt-get install python3-xlib` and see if you still get errors. Beyond this I cannot be of much help, because I'm never used  Anaconda. Maybe @nikhilkumarsingh will be able to help you out.
Thanks!

**Comment by apezoidal** [comment]
@dibyadas I have tried the `sudo apt-get install python3-xlib`but its not troubleshooting the error. 
Thanks !!

**Comment by dibyadas** [comment]
@apezoidal Oh wait. :thinking: Did you wait clix through pip or pip3 ?  If pip, then you might try to remove clix and reinstall it through pip. This might solve the error. 
Thanks.

**Comment by rish4bhn** [comment]
This issue still persists for me.
@apezoidal, Did you find a solution?

**Comment by nikhilkumarsingh** [comment]
Did you guys tried this?
https://stackoverflow.com/a/33273728

**Comment by rish4bhn** [comment]
@nikhilkumarsingh I don't use anaconda but okay, I'll install it, thanks.

**Comment by dibyadas** [comment]
@rish4bhn  Clix doesn't require anaconda. @apezoidal uses anaconda. So the stackoverflow answer was for her.  No need for you to install anaconda.

**Comment by animeshsrivastava24** [comment]
I am eagerly looking forward to contributing to this issue, please guide me with details of the error.
